# What it does: Recomputes outlet priority scores using logged visit outcomes,
#   computes moved_up / moved_down diffs, and generates a 3-line plain-English
#   explanation for the field manager via LLM (Gemini → OpenRouter → rule-based).
#
# Endpoints:
#   POST /api/recalibrate          → legacy (score update only)
#   POST /recalibrate              → new (score update only)
#   POST /api/recalibrate/explain  → score update + 3-line manager explanation
#
# Formula: final_score = 80% model score + 20% historical conversion rate
# Called by: frontend Recalibrate button, manager dashboard

from fastapi import APIRouter, Depends, Query
from db.database import get_db
from services.scoring import rank_outlets
from datetime import date, timedelta

router = APIRouter(tags=["recalibrate"])


# ── Legacy + new score-only endpoints (unchanged contract) ────────────────────

@router.post("/api/recalibrate")
async def recalibrate_legacy(rep_id: int = 1, db=Depends(get_db)):
    """Legacy recalibrate endpoint — kept for backward compatibility."""
    result = await _do_recalibrate(rep_id, db)
    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "message":         f"Rankings updated using {result['stats']['log_count']} outcome records",
    }


@router.post("/recalibrate")
async def recalibrate_new(rep_id: str = "REP_0001", db=Depends(get_db)):
    """New recalibrate endpoint — accepts string rep_id format."""
    try:
        numeric_id = int("".join(filter(str.isdigit, rep_id))) if rep_id else 1
    except ValueError:
        numeric_id = 1
    result = await _do_recalibrate(numeric_id, db)
    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "message":         f"Rankings updated using {result['stats']['log_count']} outcome records",
    }


# ── New: explain endpoint (score update + 3-line manager explanation) ──────────

@router.post("/api/recalibrate/explain")
async def recalibrate_explain(
    rep_id: str = Query("REP_0001", description="Rep ID string"),
    days:   int = Query(30,        description="Look-back window for conversion rate"),
    db=Depends(get_db)
):
    """
    Run recalibration AND return a 3-line plain-English explanation for the manager.

    Response includes:
        updated_outlets: ranked outlet list with new scores
        moved_up:        outlets that improved (with before/after scores)
        moved_down:      outlets that declined
        stats:           {log_count, sales_count, no_outcome_count, days}
        explanation:     {line1, line2, line3, full_text, source}

    Explanation is generated by: Gemini 1.5 Flash → OpenRouter LLaMA-3 → rule-based fallback
    Formula used: final_score = 80% model score + 20% historical conversion rate
    """
    try:
        numeric_id = int("".join(filter(str.isdigit, rep_id))) if rep_id else 1
    except ValueError:
        numeric_id = 1

    result = await _do_recalibrate(numeric_id, db, days=days)

    # Generate 3-line explanation
    from services.recalibration_explainer import generate_recalibration_explanation
    explanation = await generate_recalibration_explanation(
        moved_up=result["moved_up"],
        moved_down=result["moved_down"],
        stats=result["stats"],
    )

    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "moved_up":        result["moved_up"],
        "moved_down":      result["moved_down"],
        "stats":           result["stats"],
        "explanation":     explanation,
        "formula":         "final_score = 0.80 × model_score + 0.20 × conversion_rate × 100",
    }


# ── Core recalibration logic ──────────────────────────────────────────────────

async def _do_recalibrate(rep_id, db, days: int = 30) -> dict:
    """
    Shared recalibration logic used by all three endpoints.

    Steps:
        1. Query visit_logs for this rep over the look-back window
        2. Compute per-outlet conversion rate (wins / total visits)
        3. Get all outlets, compute baseline score via rank_outlets()
        4. Snapshot baseline scores BEFORE applying learning boost
        5. Apply: final = 80% base + 20% conversion_rate × 100
        6. Diff new scores vs baseline to get moved_up / moved_down
        7. Return ranked list + movers + stats

    Returns dict with keys: ranked, moved_up, moved_down, stats
    """
    cutoff = (date.today() - timedelta(days=days)).isoformat()

    # ── Step 1: visit outcome logs ────────────────────────────────────────────
    async with db.execute(
        """SELECT outlet_id,
                  SUM(CASE WHEN outcome IN ('sale','order','Order placed') THEN 1 ELSE 0 END) as wins,
                  COUNT(*) as total,
                  SUM(CASE WHEN outcome IS NULL OR outcome = '' THEN 1 ELSE 0 END) as no_outcome
           FROM visit_logs
           WHERE rep_id=? AND date >= ?
           GROUP BY outlet_id""",
        (rep_id, cutoff)
    ) as cursor:
        logs = await cursor.fetchall()

    # ── Step 2: conversion rate per outlet ────────────────────────────────────
    conversion   = {}
    total_wins   = 0
    total_logs   = 0
    total_no_out = 0

    for row in logs:
        if row["total"] > 0:
            conversion[row["outlet_id"]] = row["wins"] / row["total"]
        total_wins   += (row["wins"] or 0)
        total_logs   += (row["total"] or 0)
        total_no_out += (row["no_outcome"] or 0)

    # ── Step 3: outlets + baseline scores ─────────────────────────────────────
    async with db.execute("SELECT * FROM outlets") as cursor:
        outlets_raw = await cursor.fetchall()
    outlet_list = [dict(o) for o in outlets_raw]

    ranked = rank_outlets(outlet_list)  # assigns .score (baseline)

    # ── Step 4: snapshot baseline BEFORE boost ────────────────────────────────
    baseline_scores: dict[int, int] = {o["id"]: o["score"] for o in ranked}

    # ── Step 5: apply 80/20 learning boost ────────────────────────────────────
    for outlet in ranked:
        rate          = conversion.get(outlet["id"], 0.0)
        learning_boost= int(rate * 20)
        outlet["score"] = min(100, int(outlet["score"] * 0.80) + learning_boost)
        outlet["conversion_rate"] = round(rate, 3)

        if outlet["score"] >= 65:   outlet["label"] = "HIGH"
        elif outlet["score"] >= 40: outlet["label"] = "MEDIUM"
        else:                       outlet["label"] = "LOW"

    ranked.sort(key=lambda x: x["score"], reverse=True)

    # ── Step 6: compute diffs ─────────────────────────────────────────────────
    moved_up:   list[dict] = []
    moved_down: list[dict] = []

    for outlet in ranked:
        oid       = outlet["id"]
        old_score = baseline_scores.get(oid, outlet["score"])
        new_score = outlet["score"]
        delta     = new_score - old_score

        if delta > 0:
            moved_up.append({
                "name":      outlet.get("name", f"Outlet {oid}"),
                "outlet_id": oid,
                "old_score": old_score,
                "new_score": new_score,
                "delta":     delta,
            })
        elif delta < 0:
            moved_down.append({
                "name":      outlet.get("name", f"Outlet {oid}"),
                "outlet_id": oid,
                "old_score": old_score,
                "new_score": new_score,
                "delta":     delta,
            })

    # Sort movers by absolute magnitude
    moved_up.sort(key=lambda x: x["delta"], reverse=True)
    moved_down.sort(key=lambda x: x["delta"])   # most negative first

    stats = {
        "log_count":        total_logs,
        "sales_count":      total_wins,
        "no_outcome_count": total_no_out,
        "days":             days,
        "outlets_scored":   len(ranked),
        "moved_up_count":   len(moved_up),
        "moved_down_count": len(moved_down),
    }

    return {
        "ranked":    ranked,
        "moved_up":  moved_up,
        "moved_down":moved_down,
        "stats":     stats,
    }
