# What it does: Recomputes outlet priority scores using logged visit outcomes,
#   computes moved_up / moved_down diffs, and generates a 3-line plain-English
#   explanation for the field manager via LLM (Gemini → OpenRouter → rule-based).
#
# Endpoints:
#   POST /api/recalibrate          → legacy (score update only)
#   POST /recalibrate              → new (score update only)
#   POST /api/recalibrate/explain  → score update + 3-line manager explanation
#
# Formula: final_score = 80% model score + 20% historical conversion rate
# Called by: frontend Recalibrate button, manager dashboard

from fastapi import APIRouter, Depends, Query
from db.database import get_db
from services.scoring import rank_outlets
from datetime import date, timedelta

router = APIRouter(tags=["recalibrate"])


# ── Legacy + new score-only endpoints (unchanged contract) ────────────────────

@router.post("/api/recalibrate")
async def recalibrate_legacy(rep_id: str = "REP_0001", db=Depends(get_db)):
    """Legacy recalibrate endpoint — kept for backward compatibility."""
    result = await _do_recalibrate(rep_id, db)
    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "message":         f"Rankings updated using {result['stats']['log_count']} outcome records",
    }


@router.post("/recalibrate")
async def recalibrate_new(rep_id: str = "REP_0001", db=Depends(get_db)):
    """New recalibrate endpoint — accepts string rep_id format."""
    result = await _do_recalibrate(rep_id, db)
    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "message":         f"Rankings updated using {result['stats']['log_count']} outcome records",
    }


# ── New: explain endpoint (score update + 3-line manager explanation) ──────────

@router.post("/api/recalibrate/explain")
async def recalibrate_explain(
    rep_id: str = Query("REP_0001", description="Rep ID string"),
    days:   int = Query(30,        description="Look-back window for conversion rate"),
    db=Depends(get_db)
):
    """
    Run recalibration AND return a 3-line plain-English explanation for the manager.

    Response includes:
        updated_outlets: ranked outlet list with new scores
        moved_up:        outlets that improved (with before/after scores)
        moved_down:      outlets that declined
        stats:           {log_count, sales_count, no_outcome_count, days}
        explanation:     {line1, line2, line3, full_text, source}

    Explanation is generated by: Gemini 1.5 Flash → OpenRouter LLaMA-3 → rule-based fallback
    Formula used: final_score = 80% model score + 20% historical conversion rate
    """
    result = await _do_recalibrate(rep_id, db, days=days)

    # Generate 3-line explanation
    from services.recalibration_explainer import generate_recalibration_explanation
    explanation = await generate_recalibration_explanation(
        moved_up=result["moved_up"],
        moved_down=result["moved_down"],
        stats=result["stats"],
    )

    return {
        "success":         True,
        "updated_outlets": result["ranked"],
        "moved_up":        result["moved_up"],
        "moved_down":      result["moved_down"],
        "stats":           result["stats"],
        "explanation":     explanation,
        "formula":         "final_score = 0.80 × model_score + 0.20 × conversion_rate × 100",
    }


# ── FIX 6: weekly learning trend for the manager dashboard ────────────────────

@router.get("/api/recalibrate/history")
async def recalibrate_history(db=Depends(get_db)):
    """
    Weekly acceptance-rate trend computed from all logged visit outcomes.
    Powers the Manager → Weekly Learning bar chart.

    Returns:
        weeks:      [{week, visits, acceptance_rate}, ...]  (oldest → newest, max 8)
        trend:      "improving" | "declining" | "stable"   (last 2 weeks compared)
        total_logs: total visit_logs counted
    """
    weeks = []
    try:
        async with db.execute(
            """SELECT strftime('%W-%Y', date) AS week_key,
                      COUNT(*) AS visits,
                      ROUND(SUM(CASE WHEN outcome='sale' THEN 1.0 ELSE 0 END)
                            * 100.0 / COUNT(*), 1) AS acceptance_rate
               FROM visit_logs
               WHERE date IS NOT NULL AND date != ''
               GROUP BY week_key
               ORDER BY week_key ASC
               LIMIT 8"""
        ) as cur:
            rows = await cur.fetchall()
        for r in rows:
            weeks.append({
                "week":            r["week_key"],
                "visits":          r["visits"] or 0,
                "acceptance_rate": r["acceptance_rate"] if r["acceptance_rate"] is not None else 0.0,
            })
    except Exception as e:
        print(f"[recalibrate/history] query failed: {e}")

    total_logs = sum(w["visits"] for w in weeks)

    # Trend: compare last two weeks' acceptance rate
    trend = "stable"
    if len(weeks) >= 2:
        last, prev = weeks[-1]["acceptance_rate"], weeks[-2]["acceptance_rate"]
        if last > prev + 2:
            trend = "improving"
        elif last < prev - 2:
            trend = "declining"

    return {"weeks": weeks, "trend": trend, "total_logs": total_logs}


# ── Core recalibration logic ──────────────────────────────────────────────────

async def _do_recalibrate(rep_id, db, days: int = 30) -> dict:
    """
    Shared recalibration logic used by all three endpoints.

    Steps:
        1. Query visit_logs for this rep over the look-back window
        2. Compute per-outlet conversion rate (wins / total visits)
        3. Get all outlets, compute baseline score via rank_outlets()
        4. Snapshot baseline scores BEFORE applying learning boost
        5. Apply: final = 80% base + 20% conversion_rate × 100
        6. Diff new scores vs baseline to get moved_up / moved_down
        7. Return ranked list + movers + stats

    Returns dict with keys: ranked, moved_up, moved_down, stats
    """
    cutoff = (date.today() - timedelta(days=days)).isoformat()

    # ── Step 1: visit outcome logs ────────────────────────────────────────────
    # FIXED: no `outcome_score > 0` filter anywhere — every visit (including
    # rejections) is counted so 'none' outcomes can actively pull the rate down.
    async with db.execute(
        """SELECT outlet_id,
                  SUM(CASE WHEN outcome IN ('sale','order','Order placed') THEN 1 ELSE 0 END) as wins,
                  COUNT(*) as total,
                  SUM(CASE WHEN outcome IS NULL OR outcome = '' THEN 1 ELSE 0 END) as no_outcome,
                  SUM(CASE WHEN outcome='sale' THEN 1.0 ELSE 0 END) as sale_count,
                  SUM(CASE WHEN outcome='none' THEN 1.0 ELSE 0 END) as none_count,
                  AVG(COALESCE(outcome_score, 0)) as avg_score
           FROM visit_logs
           WHERE rep_id=? AND date >= ?
           GROUP BY outlet_id""",
        (rep_id, cutoff)
    ) as cursor:
        logs = await cursor.fetchall()

    # ── Step 2: conversion rate per outlet ────────────────────────────────────
    conversion   = {}
    avg_scores   = {}   # per-outlet average outcome_score (may be negative)
    total_wins   = 0
    total_logs   = 0
    total_no_out = 0

    for row in logs:
        if row["total"] > 0:
            # FIXED: adjusted conversion rate = (sales − 0.25·rejections) / visits.
            # Rejections (outcome='none') now actively downvote the outlet instead of
            # being ignored, so a heavily-rejected outlet gets a NEGATIVE rate.
            conversion[row["outlet_id"]] = (
                (row["sale_count"] - 0.25 * row["none_count"]) / row["total"]
            )
        avg_scores[row["outlet_id"]] = row["avg_score"] or 0.0
        total_wins   += (row["wins"] or 0)
        total_logs   += (row["total"] or 0)
        total_no_out += (row["no_outcome"] or 0)

    # ── Step 3: outlets + baseline scores ─────────────────────────────────────
    async with db.execute("SELECT * FROM outlets") as cursor:
        outlets_raw = await cursor.fetchall()
    outlet_list = [dict(o) for o in outlets_raw]

    ranked = rank_outlets(outlet_list)  # assigns .score (baseline)

    # ── Step 4: snapshot baseline BEFORE boost ────────────────────────────────
    baseline_scores: dict[int, int] = {o["id"]: o["score"] for o in ranked}

    # ── Step 5: apply 80/20 learning boost ────────────────────────────────────
    for outlet in ranked:
        rate          = conversion.get(outlet["id"], 0.0)
        learning_boost= int(rate * 20)
        # FIXED BUG 7: treat a negative average outcome_score as an active downvote —
        # subtract a penalty (up to 20 pts) so actively-rejected outlets drop below baseline.
        avg           = avg_scores.get(outlet["id"], 0.0)
        downvote_penalty = int(min(20, -avg)) if avg < 0 else 0
        outlet["score"] = max(0, min(100, int(outlet["score"] * 0.80) + learning_boost - downvote_penalty))
        outlet["conversion_rate"] = round(rate, 3)

        if outlet["score"] >= 65:   outlet["label"] = "HIGH"
        elif outlet["score"] >= 40: outlet["label"] = "MEDIUM"
        else:                       outlet["label"] = "LOW"

    ranked.sort(key=lambda x: x["score"], reverse=True)

    # ── Step 6: compute diffs ─────────────────────────────────────────────────
    moved_up:   list[dict] = []
    moved_down: list[dict] = []

    for outlet in ranked:
        oid       = outlet["id"]
        old_score = baseline_scores.get(oid, outlet["score"])
        new_score = outlet["score"]
        delta     = new_score - old_score

        if delta > 0:
            moved_up.append({
                "name":      outlet.get("name", f"Outlet {oid}"),
                "outlet_id": oid,
                "old_score": old_score,
                "new_score": new_score,
                "delta":     delta,
            })
        elif delta < 0:
            moved_down.append({
                "name":      outlet.get("name", f"Outlet {oid}"),
                "outlet_id": oid,
                "old_score": old_score,
                "new_score": new_score,
                "delta":     delta,
            })

    # Sort movers by absolute magnitude
    moved_up.sort(key=lambda x: x["delta"], reverse=True)
    moved_down.sort(key=lambda x: x["delta"])   # most negative first

    stats = {
        "log_count":        total_logs,
        "sales_count":      total_wins,
        "no_outcome_count": total_no_out,
        "days":             days,
        "outlets_scored":   len(ranked),
        "moved_up_count":   len(moved_up),
        "moved_down_count": len(moved_down),
    }

    return {
        "ranked":    ranked,
        "moved_up":  moved_up,
        "moved_down":moved_down,
        "stats":     stats,
    }
